"""Import the generated .apkg with the real Anki engine and verify it."""
import os, re, shutil, sys, tempfile
import anki
from anki.collection import Collection

APKG = "/home/claude/out/PSYC101-Chapter-0.apkg"
print("anki lib:", anki.buildinfo.version)

tmp = tempfile.mkdtemp()
col = Collection(os.path.join(tmp, "test.anki2"))

from anki.collection import ImportAnkiPackageRequest, ImportAnkiPackageOptions
req = ImportAnkiPackageRequest(package_path=APKG, options=ImportAnkiPackageOptions())
out = col.import_anki_package(req)
print("import log:", str(out.log)[:400].replace("\n", " "))

nids = col.find_notes("")
cids = col.find_cards("")
print(f"\nnotes imported: {len(nids)}   cards generated by Anki: {len(cids)}")

# note types
for m in col.models.all():
    names = [f["name"] for f in m["flds"]]
    print(f"  notetype {m['name']!r} type={m['type']} fields={names}")

# decks
print("  decks:", sorted(d.name for d in col.decks.all_names_and_ids()))

fails = []

# 1. hidden premedos_* fields must not render on any card
leak = 0
for cid in cids:
    card = col.get_card(cid)
    q, a = card.question(), card.answer()
    if "intro-psych:" in a or "flashcards-v1@" in a or "psychlecture01notes" in a:
        leak += 1
print(f"\n[1] hidden-field leakage into rendered cards: {leak}")
if leak: fails.append("premedos_* fields render during review (FC-15)")

# 2. every card renders a non-empty question distinct from its answer
empty = [cid for cid in cids if not re.sub(r"<[^>]+>|\s", "", col.get_card(cid).question())]
print(f"[2] cards with an empty question side: {len(empty)}")
if empty: fails.append("empty question side")

# 3. cloze notes generated the expected number of cards
from deck_cards import CARDS
expected_cards = sum(
    len({int(n) for n in re.findall(r"\{\{c(\d+)::", c["cz"])}) if c.get("cp") else 1
    for c in CARDS)
print(f"[3] expected cards {expected_cards} vs anki-generated {len(cids)}")
if expected_cards != len(cids): fails.append("card count mismatch")
if len(nids) != len(CARDS): fails.append("note count mismatch")

# 4. all cards are new/unseen — no scheduling state shipped (FC-EXP-6)
sched = [cid for cid in cids if col.get_card(cid).type != 0 or col.get_card(cid).reps]
print(f"[4] cards carrying scheduling state: {len(sched)}  (must be 0 — FC-EXP-6)")
if sched: fails.append("scheduling state present")

# 5. every note carries concept id, source and spec
missing = []
for nid in nids:
    n = col.get_note(nid)
    d = dict(zip([f["name"] for f in n.note_type()["flds"]], n.fields))
    if not d.get("premedos_concept_id") or not d.get("premedos_source") or not d.get("premedos_spec"):
        missing.append(nid)
print(f"[5] notes missing provenance fields: {len(missing)}  (FC-EXP-1/3)")
if missing: fails.append("missing provenance")

# 6. cloze rendering actually blanks something
cloze_bad = []
for cid in cids:
    card = col.get_card(cid)
    if card.note_type()["type"] != 1:
        continue
    if "[...]" not in card.question() and "cloze-inactive" not in card.question():
        cloze_bad.append(cid)
print(f"[6] cloze cards not showing a blank: {len(cloze_bad)}")
if cloze_bad: fails.append("cloze not blanking")

# 7. duplicate detection using anki's own checksum index
dupes = 0
seen = {}
for nid in nids:
    n = col.get_note(nid)
    key = (n.mid, n.fields[0])
    if key in seen: dupes += 1
    seen[key] = nid
print(f"[7] exact duplicate first-fields: {dupes}")
if dupes: fails.append("duplicates")

# 8. anki's own database check
prob = col.fix_integrity()
print(f"[8] anki fix_integrity: {str(prob)[:200]}")

# sample render
print("\n--- sample rendered card (basic) ---")
for cid in cids:
    card = col.get_card(cid)
    if card.note_type()["type"] == 0:
        print("Q:", re.sub(r"<[^>]+>", " ", card.question()).strip()[:200])
        print("A:", re.sub(r"<[^>]+>", " ", card.answer()).strip()[:400])
        break
print("\n--- sample rendered card (cloze) ---")
for cid in cids:
    card = col.get_card(cid)
    if card.note_type()["type"] == 1:
        print("Q:", re.sub(r"<[^>]+>", " ", card.question()).strip()[:250])
        print("A:", re.sub(r"<[^>]+>", " ", card.answer()).strip()[:400])
        break

col.close()
shutil.rmtree(tmp, ignore_errors=True)
print("\n" + ("FAILURES: " + "; ".join(fails) if fails else "ALL CHECKS PASSED"))
sys.exit(1 if fails else 0)
