import { deflateRawSync } from 'node:zlib'
import { notebookCrc32 } from './notebookZip'
/** Ordinary ZIP as generated by Python/AI tools, including deflated members and directory records. */
export function plainNotebookZip(files: [string, Uint8Array][], compressed = true): Blob {
  const parts: BlobPart[] = [], central: Uint8Array[] = []; let offset = 0, centralSize = 0
  for (const [path, bytes] of files) {
    const name = new TextEncoder().encode(path), body = compressed ? new Uint8Array(deflateRawSync(bytes)) : bytes, method = compressed ? 8 : 0, crc = notebookCrc32(bytes)
    const local = new Uint8Array(30 + name.length), lv = new DataView(local.buffer)
    lv.setUint32(0, 0x04034b50, true); lv.setUint16(4, 20, true); lv.setUint16(6, 0x800, true); lv.setUint16(8, method, true); lv.setUint32(14, crc, true); lv.setUint32(18, body.length, true); lv.setUint32(22, bytes.length, true); lv.setUint16(26, name.length, true); local.set(name, 30)
    const header = new Uint8Array(46 + name.length), cv = new DataView(header.buffer)
    cv.setUint32(0, 0x02014b50, true); cv.setUint16(4, 0x314, true); cv.setUint16(6, 20, true); cv.setUint16(8, 0x800, true); cv.setUint16(10, method, true); cv.setUint32(16, crc, true); cv.setUint32(20, body.length, true); cv.setUint32(24, bytes.length, true); cv.setUint16(28, name.length, true); cv.setUint32(38, path.endsWith('/') ? 0x40000000 : 0x80000000, true); cv.setUint32(42, offset, true); header.set(name, 46)
    parts.push(local, body.slice().buffer); central.push(header); offset += local.length + body.length; centralSize += header.length
  }
  const end = new Uint8Array(22), ev = new DataView(end.buffer)
  ev.setUint32(0, 0x06054b50, true); ev.setUint16(8, files.length, true); ev.setUint16(10, files.length, true); ev.setUint32(12, centralSize, true); ev.setUint32(16, offset, true)
  return new Blob([...parts, ...central.map(part => part.slice().buffer), end], { type: 'application/zip' })
}
