import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { useStore } from '@/store/store'
import { composeNotebookPrompt, type PromptValues } from '@/lib/academics/notebook/prompt'
import type { NotebookGoal } from '@/lib/academics/notebook/types'
import { NotebookImportPanel } from './NotebookImportPanel'
import { downloadNotebookText, notebookTransaction } from './ExternalNotebookView'
const GOALS = { review: { title: 'Review class material', description: 'Connected explanations, source-backed mastery objectives, and recall practice.', stages: ['Understand and connect', 'Practice recall', 'Revisit weak areas'] }, assessment: { title: 'Prepare for an assessment', description: 'Map the full assessment scope across lessons and materials, then practice.', stages: ['Establish scope and coverage', 'Explain difficult topics', 'Practice and identify gaps'] }, assignment: { title: 'Work on an assignment', description: 'Use the prompt, rubric, and your attempt to work through the current stage.', stages: ['Understand the task', 'Plan an approach', 'Get a hint', 'Review my attempt', 'Revise my draft'] } }
export function ExternalNotebookWorkflow({ courseId, onImported }: { courseId: string; onImported: (id: string) => void }) {
  const course = useStore(s => s.courses.find(c => c.id === courseId))
  const workspace = useStore(s => s.academics.classCenter.workspaces.find(w => w.courseId === courseId))
  const files = useStore(s => s.academics.classCenter.files)
  const [step, setStep] = useState(0)
  const [goal, setGoal] = useState<NotebookGoal>('review')
  const [preferences, setPreferences] = useState(workspace?.externalNotebookPreferences ?? '')
  const [scope, setScope] = useState('')
  const [scopeSource, setScopeSource] = useState('')
  const [materials, setMaterials] = useState('')
  const [selected, setSelected] = useState<string[]>([])
  const [stage, setStage] = useState(GOALS.review.stages[0])
  const [format, setFormat] = useState('')
  const [depth, setDepth] = useState('Full explanation with connections, examples, and practice')
  const [request, setRequest] = useState('')
  const [term, setTerm] = useState(course?.term ?? '')
  const [message, setMessage] = useState('')
  if (!course) return <p role="alert">Class not found.</p>
  const values: PromptValues = { COURSE_CODE: course.code, COURSE_TITLE: course.title, TERM: term || null, SCOPE: scope.trim() ? `${scope}\nScope authority: ${scopeSource || 'Not supplied; label provisional scope.'}` : null, MATERIALS: [...files.filter(f => f.courseId === courseId && selected.includes(f.id)).map(f => `${f.title} (${f.type}; attach the actual original file in the AI conversation)`), materials].filter(Boolean).join('\n'), DEPTH: depth, CLASS_PREFERENCES: preferences, HELP_STAGE: stage, ASSESSMENT_FORMAT: goal === 'assessment' ? format || null : null, USER_REQUEST: request, REVISION_INPUT: null }
  const fullPrompt = composeNotebookPrompt(goal, values)
  function savePreferences() {
    try { notebookTransaction(state => { const target = state.academics.classCenter.workspaces.find(w => w.courseId === courseId); if (!target) throw new Error('Open the class notebook once to initialize its preferences.'); target.externalNotebookPreferences = preferences }); setMessage('Class preferences saved for future prompts.') } catch (error) { setMessage((error as Error).message) }
  }
  return <section className="external-notebook" aria-label="External AI notebook workflow"><header className="en-header"><div><p className="en-eyebrow">{course.code} / Class notebook</p><h1>{step === 0 ? 'What would you like to do?' : step === 1 ? 'Make this fit your class' : step === 2 ? 'Take one full prompt to your AI' : 'Bring back your notebook'}</h1></div><Button variant="outline" onClick={() => setStep(3)}>Already have JSON? Import directly</Button></header>
    <nav className="en-stepnav" aria-label="Notebook workflow progress">{['Goal', 'Details (optional)', 'Use your AI', 'Import and save'].map((label, i) => <span key={label} aria-current={step === i ? 'step' : undefined}>{i + 1}. {label}</span>)}</nav>
    {step === 0 && <><p>Choose one of three prepared prompts. You will copy it into your preferred AI, attach your class materials there, and bring the finished notebook back here.</p><fieldset><legend className="sr-only">Notebook goal</legend><div className="en-goals">{(Object.keys(GOALS) as NotebookGoal[]).map(g => <label key={g} className="rounded-xl border bg-card p-5"><input aria-label={GOALS[g].title} type="radio" name={`external-goal-${courseId}`} value={g} checked={goal === g} onChange={() => { setGoal(g); setStage(GOALS[g].stages[0]) }} /><b className="ml-2">{GOALS[g].title}</b><p>{GOALS[g].description}</p></label>)}</div></fieldset><label className="en-field">Anything specific? <span className="en-muted">Optional</span><textarea value={request} onChange={e => setRequest(e.target.value)} placeholder="e.g., explain simply, give examples, focus on a topic..." /></label><div className="en-actions"><Button onClick={() => setStep(2)}>View full prompt</Button><Button variant="outline" onClick={() => setStep(1)}>Customize prompt</Button></div></>}
    {step === 1 && <><h2>{GOALS[goal].title}</h2><label className="en-field">Class preferences<textarea value={preferences} onChange={e => setPreferences(e.target.value)} placeholder="Instructor terminology, explanation style, connections, writing conventions..." /></label><Button variant="outline" onClick={savePreferences}>Remember preferences for this class</Button><label className="en-field">Term (optional)<input value={term} onChange={e => setTerm(e.target.value)} placeholder="Fall 2026" /></label>
      {goal === 'assessment' && <div className="en-notice"><b>Establish the assessment scope first</b><p>Use the instructor's review sheet or topic list as the scope authority. List every included lesson, reading, and requirement below, then select materials that support each one. Ask the AI to mark each requirement supported, partial, missing, or out of scope. An unknown format or missing review sheet must remain visible.</p></div>}
      <label className="en-field">{goal === 'assessment' ? 'Included lessons, readings, and assessment topics' : 'Scope for this entry'}<textarea value={scope} onChange={e => setScope(e.target.value)} placeholder={goal === 'assessment' ? 'Lessons 1-5; readings A and B; every item on the Exam 1 review sheet...' : 'Name the lesson, reading, task, or topic you want to work through.'} /></label>
      <label className="en-field">{goal === 'assignment' ? 'Assignment prompt or rubric defining the task' : 'Source defining the scope'}<textarea value={scopeSource} onChange={e => setScopeSource(e.target.value)} placeholder={goal === 'assessment' ? 'Instructor review sheet, dated topic list, or my provisional topic selection...' : 'Official objectives, instructor instructions, or my own selected topics...'} /></label>
      {goal === 'assessment' && <label className="en-field">Assessment format (leave blank if unknown)<input value={format} onChange={e => setFormat(e.target.value)} placeholder="Multiple choice, short answer, essay, problem solving..." /></label>}
      <label className="en-field">Help stage<select value={stage} onChange={e => setStage(e.target.value)}>{GOALS[goal].stages.map(s => <option key={s}>{s}</option>)}</select></label><label className="en-field">Depth and style<input value={depth} onChange={e => setDepth(e.target.value)} /></label>
      <h3>Materials for this scope</h3><p>Select any saved class materials you plan to attach, and list additional files. This creates an attachment checklist; it does not attach files to your AI.</p>{files.some(f => f.courseId === courseId) && <div className="en-materials" aria-label="Saved class materials">{files.filter(f => f.courseId === courseId).map(f => <label key={f.id} className="en-check"><input type="checkbox" checked={selected.includes(f.id)} onChange={e => setSelected(e.target.checked ? [...selected, f.id] : selected.filter(id => id !== f.id))} />{f.title} / {f.type}</label>)}</div>}
      <label className="en-field">Other materials you will attach<textarea value={materials} onChange={e => setMaterials(e.target.value)} placeholder={goal === 'assignment' ? 'Assignment prompt, rubric, required reading, my draft or attempted solution...' : 'Review sheet, notes for each lesson, slides, readings, practice questions, answer keys...'} /></label><label className="en-field">Anything specific you want help with?<textarea value={request} onChange={e => setRequest(e.target.value)} /></label><div className="en-actions"><Button variant="outline" onClick={() => setStep(0)}>Back to goal</Button><Button onClick={() => setStep(2)}>View full prompt</Button></div>{(!scope.trim() || (!materials.trim() && !selected.length)) && <p className="en-muted">Details are optional. Tell your AI the scope and attach the materials in that conversation before it creates the notebook.</p>}</>}
    {step === 2 && <><p>This is the prepared {GOALS[goal].title.toLowerCase()} prompt, with your class details inserted locally. It includes the full instructions and the notebook JSON format.</p><Button variant="outline" onClick={() => setStep(1)}>Optional class details and scope</Button><ol className="list-decimal space-y-2 pl-6"><li>Copy the full prompt into your preferred AI conversation.</li><li>Attach every original material listed below. Verify the AI reports what it could actually read.</li><li>Ask for a downloadable .json file, or the complete JSON block if file downloads are unavailable.</li><li>Return here to validate, preview, and save into {course.code}.</li></ol><div className="en-notice"><b>Attachment checklist</b><p className="en-text">{values.MATERIALS || (goal === 'assessment' ? 'Start with the review sheet or assessment topic list. Attach the notes, slides, and readings for every included lesson, plus relevant practice questions and answer keys. Tell your AI the assessment format if known.' : goal === 'assignment' ? 'Attach the assignment prompt, rubric, required readings, and your draft or attempted solution. Tell your AI what stage you want help with.' : 'Attach the lecture notes or transcript, slides, assigned reading, and official learning objectives relevant to the lesson you want to review.')}</p></div><div className="en-actions"><Button onClick={() => { void navigator.clipboard.writeText(fullPrompt).then(() => setMessage('Full customized prompt copied.'), () => setMessage('Clipboard unavailable. Select the full prompt below or download it.')) }}>Copy full prompt</Button><Button variant="outline" onClick={() => downloadNotebookText(`notebook-${goal}-prompt.md`, fullPrompt, 'text/markdown')}>Download full prompt</Button></div><details><summary>Preview the exact full prompt</summary><label className="en-field">Full customized prompt<textarea className="en-json" readOnly value={fullPrompt} /></label></details><div className="en-actions"><Button variant="outline" onClick={() => setStep(1)}>Edit customization</Button><Button onClick={() => setStep(3)}>I have the JSON</Button></div></>}
    {step === 3 && <><Button variant="outline" onClick={() => setStep(0)}>Create a prompt instead</Button><NotebookImportPanel courseId={courseId} onImported={onImported} /></>}
    <p role="status" aria-live="polite">{message}</p>
  </section>
}
