/** App help only; the maintained, goal-specific AI instructions remain canonical. */
export function NotebookUpdateGuide() {
  return <details className="en-update-guide en-stage-panel">
    <summary>How to update your notebook</summary>
    <ol className="en-update-guide-steps">
      <li><h3>Save your changes</h3><p>Save or cancel unfinished notebook edits and notes before starting. The JSON contains the latest saved notebook content and retained sources. Your separate My notes, practice responses and checkmarks stay in Premed OS; they are not included.</p></li>
      <li><h3>Get both files</h3><p>Choose <b>Download current notebook JSON</b>, then <b>Copy update prompt</b>. You can use <b>Download update prompt</b> instead of copying. The JSON is the saved notebook to update; the prompt tells your AI how to update it. Use the complete prefilled prompt and its matching saved JSON.</p><p>Keep both until the updated notebook saves successfully. If this update started from an older saved version, restart from the latest saved entry and get both again.</p></li>
      <li><h3>Open your AI chat and add your materials</h3><p>Use your existing conversation or a fresh chat. Paste the complete update prompt, attach the saved notebook JSON, and add new notes, screenshots, readings or pasted material. A class project is optional; the previous chat is not required.</p><p>A whole revised notes file is fine. You do not need to identify every new sentence: the instructions ask your AI to compare repeated material, new details, corrections and conflicts. Reattach older originals only when retained evidence lacks the context needed to check a specific point.</p></li>
      <li><h3>Say what should change</h3><p>Name the new lesson or topic and the help you want. For example: "Add Thursday's Chapter 3 material to this notebook. Keep the earlier explanations and my edits, combine repeated material, and explain any corrections." Add focus preferences if useful. If a new topic belongs in another notebook, say so explicitly. Existing content should stay unless you ask to change it.</p></li>
      <li><h3>Finish uploading</h3><p>Send files or screenshots in batches your AI can handle. Tell it when you are done uploading and ask it to identify anything unreadable or still unprocessed. Finishing uploads is not approval of the revised notebook.</p></li>
      <li><h3>Review the revised notebook</h3><p>Your AI should show the complete readable draft and a short summary of additions, corrections, other changes and gaps. Check the explanations and practice, not just the summary. Ask questions or request changes. When satisfied with the current version, explicitly approve it, for example: "Create the JSON." Substantive changes need a revised draft before approval.</p></li>
      <li><h3>Download the complete revised JSON</h3><p>Get the complete revised notebook as a .json file, or copy the entire final JSON block if downloads are unavailable. A prompt, working checkpoint, chat transcript or partial patch is not the notebook to import.</p></li>
      <li><h3>Review and save in Premed OS</h3><p>Return to this same saved notebook and its <b>Update this notebook</b> flow. Import the revised JSON, check the destination and comparison, and explicitly accept the update. If the saved notebook changed after export, use its latest saved JSON and reconcile those changes first.</p><p>Earlier versions remain in history. Unaffected practice responses and checkmarks are retained; affected items may start fresh, with prior work recoverable in history. Follow this update's comparison rather than assuming every study record transfers unchanged.</p></li>
    </ol>
    <h3>If something goes wrong</h3>
    <details><summary>I lost the AI conversation</summary><p>Start a fresh chat with the complete update prompt, latest saved notebook JSON and new materials. Premed OS does not retrieve the old chat or send files to your AI automatically.</p></details>
    <details><summary>I cannot find the previous JSON</summary><p>If the notebook is saved in Premed OS, download its current JSON again and use the matching update prompt. If neither saved app content nor a usable backup survives, its title or a remembered conversation cannot recover it. Rebuild from the original materials as a new notebook; do not ask the AI to invent previous wording, edits or revision history.</p></details>
    <details><summary>A file is unreadable or I hit an upload limit</summary><p>Send a smaller batch, paste readable text, or supply clear page images with the full question, labels and diagram. Ask which parts still need attention. Uploading does not prove a file was fully read. In a new chat, carry over the saved JSON and any real working checkpoint, and identify unfinished work.</p></details>
    <details><summary>Premed OS rejects the JSON</summary><p>Give your AI the actual import error and complete file. Ask for a complete corrected JSON preserving the approved content. Do not remove sections or cut off text to make it fit. Recover truncated content; review substantive repairs in a readable draft before approving JSON. A browser storage error calls for freeing space or keeping an export, not rewriting learning content.</p></details>
    <details><summary>I edited the notebook after exporting</summary><p>Save or cancel unfinished edits. Restart from the latest saved entry, download its current JSON and copy its new update prompt. Give your AI that version and the proposed changes to preserve newer edits. Review the draft and app comparison again before accepting.</p></details>
  </details>
}
