/** App help only; the maintained, goal-specific AI instructions remain canonical. */
export function NotebookUpdateGuide() {
  return <details className="en-update-guide en-stage-panel">
    <summary>How to update your notebook</summary>
    <ol className="en-update-guide-steps">
      <li><h3>Save your changes</h3><p>Save or cancel unfinished notebook edits and notes before starting. The JSON contains the latest saved notebook content and retained sources. Your separate My notes, practice responses and checkmarks stay in Premed OS; they are not included.</p></li>
      <li><h3>Get the baseline files and prompt</h3><p>If your notebook has figures or other referenced images, choose <b>Download current baseline + images</b>. Unzip this app-exported bundle and bring <b>notebook.json</b>, the original PNG/JPEG files in <b>assets/</b>, and <b>bindings.json</b> so your AI can map the image files to the notebook asset IDs. Keep those files and their mapping together. For a text-only notebook, <b>Download current notebook JSON</b> is enough.</p><p>Then choose <b>Copy update prompt</b>, or <b>Download update prompt</b>. The JSON is the saved notebook to update; the prompt tells your AI how to update it. Use the complete prefilled prompt and its matching saved files. Keep them until the updated notebook saves successfully. If this update started from an older saved version, restart from the latest saved entry and get fresh files and the prompt.</p></li>
      <li><h3>Open your AI chat and add your materials</h3><p>Use your existing conversation or a fresh chat. Paste the complete update prompt, attach the saved notebook JSON and any existing referenced image files with their mapping, and add new notes, screenshots, readings or pasted material. A class project is optional; the previous chat is not required. JSON filenames alone do not supply image bytes.</p><p>A whole revised notes file is fine. You do not need to identify every new sentence: the instructions ask your AI to compare repeated material, new details, corrections and conflicts. Reattach older source documents when retained evidence lacks the context needed to check a specific point; existing referenced images still travel with the baseline.</p></li>
      <li><h3>Say what should change</h3><p>Name the new lesson or topic and the help you want. For example: "Add Thursday's Chapter 3 material to this notebook. Keep the earlier explanations and my edits, combine repeated material, and explain any corrections." Add focus preferences if useful. If a new topic belongs in another notebook, say so explicitly. Existing content should stay unless you ask to change it.</p></li>
      <li><h3>Finish uploading</h3><p>Send files or screenshots in batches your AI can handle. If you say more files are coming, it should wait until you say you are done uploading. Ask it to identify anything unreadable or still unprocessed. Without a pending batch, no special completion phrase is required.</p></li>
      <li><h3>Get the revised notebook</h3><p>Your AI should check the sources and content, then provide a complete titled ZIP containing the revised JSON and all required PNG/JPEG images, with a short summary of additions, corrections and gaps. No separate draft approval is required. You can request a readable draft, ask questions or discuss changes if useful.</p></li>
      <li><h3>Download the complete revised notebook and images</h3><p>Download the complete revised ZIP named after the notebook. Extract it and keep the folder intact, including its JSON, new or revised PNG/JPEG images and unchanged originals. If ZIP creation is unavailable, keep the complete delivered folder or file set together. Use a complete JSON block only when file downloads are unavailable; add every required actual image separately. Browser settings control the save location. A text-only notebook needs no image files. A prompt, working checkpoint, chat transcript or partial patch is not the notebook to import.</p></li>
      <li><h3>Review and save in Premed OS</h3><p>Return to this same saved notebook and its <b>Update this notebook</b> flow. Choose the revised notebook folder, or open Other import options to upload its ZIP. Check the destination and comparison, and explicitly accept the update. If the saved notebook changed after export, use its latest saved baseline and image files and reconcile those changes first.</p><p>Earlier versions remain in history. Unaffected practice responses and checkmarks are retained; affected items may start fresh, with prior work recoverable in history. Follow this update's comparison rather than assuming every study record transfers unchanged.</p></li>
    </ol>
    <h3>If something goes wrong</h3>
    <details><summary>I lost the AI conversation</summary><p>Start a fresh chat with the complete update prompt, latest saved notebook JSON, its existing referenced image files and mapping, and new materials. If there are figures, download and unzip the current baseline + images bundle as described above; a text-only notebook needs only JSON and the prompt. Premed OS does not retrieve the old chat or send files to your AI automatically.</p></details>
    <details><summary>I cannot find the previous JSON</summary><p>If the notebook is saved in Premed OS, download its current baseline + images again, or current JSON for a text-only notebook, and use the matching update prompt. If an image is missing locally, restore it from a complete portable backup or recover its exact original file before exporting again. Never replace a missing image with different bytes under its existing ID. If neither saved app content nor a usable backup survives, its title or a remembered conversation cannot recover it. Rebuild from the original materials as a new notebook; do not ask the AI to invent previous wording, edits or revision history.</p></details>
    <details><summary>A file is unreadable or I hit an upload limit</summary><p>Send a smaller batch, paste readable text, or supply clear page images with the full question, labels and diagram. Ask which parts still need attention. Uploading does not prove a file was fully read. In a new chat, carry over the saved JSON, its referenced image files and mapping, and any real working checkpoint, and identify unfinished work.</p></details>
    <details><summary>Premed OS rejects the notebook</summary><p>Give your AI the actual import error and complete file. Ask for a complete corrected ZIP with the notebook JSON and all required images, preserving the notebook content. If ZIP creation is unavailable, request the complete folder or downloadable file set. Do not remove sections or cut off text to make it fit. Recover truncated content and ask it to explain substantive repairs with the corrected file. A readable draft is optional. A browser storage error calls for freeing space or keeping an export, not rewriting learning content.</p></details>
    <details><summary>I edited the notebook after exporting</summary><p>Save or cancel unfinished edits. Restart from the latest saved entry, download its current baseline + images, or JSON for a text-only notebook, and copy its new update prompt. Give your AI that version, its referenced image files and mapping, and the proposed changes to preserve newer edits. Review the updated notebook and app comparison again before accepting.</p></details>
  </details>
}
