"""Hand-rolled .apkg writer (04 §14.4 — no Anki dependency).

Emits Anki schema-11 collection.anki2 with the two premedOS note types
specified in 04 §14.2. Export is one-way (FC-EXP-2); nothing is read back.
"""
import hashlib, json, os, re, sqlite3, time, zipfile, random
from lesson2_revised_cards import CARDS

OUT = "/Users/andyquach/Downloads/BIOL103-Lesson2-Transcription-Translation-Protein-Targeting-revised.apkg"
os.makedirs(os.path.dirname(OUT), exist_ok=True)

COURSE_ID, TOPIC_ID = "biol103", "lesson-2"
DECK_SUB = "UNC::Fall 2026::BIOL103::Lesson 2"   # FC-EXP-5, Andy's deck tree
SPEC = "flashcards-v1@aug-2026-relate-revision"
PRESET, MODE = "premedos-default", "SOURCE_ONLY"

# ── ids ─────────────────────────────────────────────────────────────────────
now_ms = int(time.time() * 1000)
crt = int(time.mktime(time.strptime("2026-08-20", "%Y-%m-%d")))
MID_BASIC, MID_CLOZE = 1755000000001, 1755000000002
DID_UNC, DID_TERM, DID_COURSE, DID_SUB = (1755000000010, 1755000000011,
                                          1755000000012, 1755000000013)

B91 = ("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
       "!#$%&()*+,-./:;<=>?@[]^_`{|}~")
def guid64(seed):
    rnd = random.Random(seed)
    x = rnd.getrandbits(64)
    s = ""
    while x:
        x, r = divmod(x, len(B91))
        s = B91[r] + s
    return s or "a"

def csum(field0):
    txt = re.sub(r"<[^>]+>", "", field0)
    return int(hashlib.sha1(txt.encode()).hexdigest()[:8], 16)

def slug(s):
    return re.sub(r"-+", "-", re.sub(r"[^a-z0-9]+", "-", s.lower())).strip("-")

def esc(s):
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
             if not re.search(r"</?(b|i|u|br|div|span)\b", s) else s)

def hard_esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

def blurt_back(items):
    """FREE_RECALL back = an ordered, independently gradeable checklist (FC-FR-3/4)."""
    lis = "".join(f"<li>{hard_esc(it)}</li>" for it in items)
    return f'<ol class="blurt">{lis}</ol>'

def blurt_front(front):
    return hard_esc(front)

# ── note types (04 §14.2) ───────────────────────────────────────────────────
CSS = open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       "biol_card-styles.css"), encoding="utf-8").read()
# Design lives in card-styles.css, not here. See README.md "Design".

EXTRA_TMPL = ('{{#Extra}}<div class="extra">'
              '<span class="extra-label">Extra</span>{{Extra}}</div>{{/Extra}}')
TYPE_TMPL = '<div class="type">{{Type}}</div>'


def fld(name, ord_, sticky=False):
    return dict(name=name, ord=ord_, sticky=sticky, rtl=False, font="Arial",
                size=20, media=[], description="")

BASIC_FIELDS = ["Front", "Back", "Extra", "Type", "Mindset",
                "premedos_concept_id", "premedos_source", "premedos_spec"]
CLOZE_FIELDS = ["Text", "Extra", "Type", "Mindset",
                "premedos_concept_id", "premedos_source", "premedos_spec"]

models = {
    str(MID_BASIC): dict(
        id=MID_BASIC, name="premedOS Basic", type=0, mod=now_ms // 1000, usn=-1,
        sortf=0, did=DID_SUB, latexPre="", latexPost="", latexsvg=False,
        flds=[fld(n, i) for i, n in enumerate(BASIC_FIELDS)],
        tmpls=[dict(name="Card 1", ord=0, did=None, bqfmt="", bafmt="",
                    qfmt='<div class="pm {{Mindset}}">' + TYPE_TMPL + '{{Front}}</div>',
                    afmt='<div class="pm {{Mindset}}">' + TYPE_TMPL + '{{Front}}'
                         '<hr id=answer><div class="answer">{{Back}}</div>' + EXTRA_TMPL + '</div>')],
        css=CSS, req=[[0, "any", [0]]], tags=[], vers=[]),
    str(MID_CLOZE): dict(
        id=MID_CLOZE, name="premedOS Cloze", type=1, mod=now_ms // 1000, usn=-1,
        sortf=0, did=DID_SUB, latexPre="", latexPost="", latexsvg=False,
        flds=[fld(n, i) for i, n in enumerate(CLOZE_FIELDS)],
        tmpls=[dict(name="Cloze", ord=0, did=None, bqfmt="", bafmt="",
                    qfmt='<div class="pm {{Mindset}}">' + TYPE_TMPL + '{{cloze:Text}}</div>',
                    afmt='<div class="pm {{Mindset}}">' + TYPE_TMPL + '{{cloze:Text}}' + EXTRA_TMPL + '</div>')],
        css=CSS, req=[[0, "any", [0]]], tags=[], vers=[]),
}
# premedos_* fields appear in NO template -> hidden during review (04 §14.2, FC-15)

def deck(did, name):
    return dict(id=did, name=name, mod=now_ms // 1000, usn=-1, lrnToday=[0, 0],
                revToday=[0, 0], newToday=[0, 0], timeToday=[0, 0], collapsed=False,
                browserCollapsed=False, desc="", dyn=0, conf=1, extendNew=10, extendRev=50)

decks = {
    "1": deck(1, "Default"),
    str(DID_UNC): deck(DID_UNC, "UNC"),
    str(DID_TERM): deck(DID_TERM, "UNC::Fall 2026"),
    str(DID_COURSE): deck(DID_COURSE, "UNC::Fall 2026::BIOL103"),
    str(DID_SUB): deck(DID_SUB, DECK_SUB),
}
decks[str(DID_SUB)]["desc"] = (
    f"Generated by premedOS · spec {SPEC} · preset {PRESET} · source mode {MODE}. "
    "Built only from your supplied BIOL 103 Lesson 2 material. "
    "Review and scheduling live here in Anki; premedOS never reads this deck back."
)

dconf = {"1": dict(id=1, name="Default", mod=0, usn=0, maxTaken=60, autoplay=True,
                   timer=0, replayq=True,
                   new=dict(bury=False, delays=[1.0, 10.0], initialFactor=2500,
                            ints=[1, 4, 0], order=1, perDay=25),
                   rev=dict(bury=False, ease4=1.3, ivlFct=1.0, maxIvl=36500,
                            perDay=200, hardFactor=1.2),
                   lapse=dict(delays=[10.0], leechAction=1, leechFails=8,
                              minInt=1, mult=0.0),
                   dyn=False, newMix=0, newPerDayMinimum=0, interdayLearningMix=0,
                   reviewOrder=0)}

conf = dict(nextPos=1, estTimes=True, activeDecks=[DID_SUB], sortType="noteFld",
            timeLim=0, sortBackwards=False, addToCur=True, curDeck=DID_SUB,
            newBury=True, newSpread=0, dueCounts=True, curModel=str(MID_BASIC),
            collapseTime=1200, schedVer=2, dayLearnFirst=False)

# ── build ───────────────────────────────────────────────────────────────────
db = os.path.join(os.path.dirname(os.path.abspath(__file__)), "biol-reference-build.anki2")
if os.path.exists(db):
    os.remove(db)
con = sqlite3.connect(db)
c = con.cursor()
c.executescript("""
CREATE TABLE col (id integer primary key, crt integer not null, mod integer not null,
  scm integer not null, ver integer not null, dty integer not null, usn integer not null,
  ls integer not null, conf text not null, models text not null, decks text not null,
  dconf text not null, tags text not null);
CREATE TABLE notes (id integer primary key, guid text not null, mid integer not null,
  mod integer not null, usn integer not null, tags text not null, flds text not null,
  sfld integer not null, csum integer not null, flags integer not null, data text not null);
CREATE TABLE cards (id integer primary key, nid integer not null, did integer not null,
  ord integer not null, mod integer not null, usn integer not null, type integer not null,
  queue integer not null, due integer not null, ivl integer not null, factor integer not null,
  reps integer not null, lapses integer not null, left integer not null, odue integer not null,
  odid integer not null, flags integer not null, data text not null);
CREATE TABLE graves (usn integer not null, oid integer not null, type integer not null);
CREATE TABLE revlog (id integer primary key, cid integer not null, usn integer not null,
  ease integer not null, ivl integer not null, lastIvl integer not null, factor integer not null,
  time integer not null, type integer not null);
CREATE INDEX ix_notes_usn on notes (usn);
CREATE INDEX ix_cards_usn on cards (usn);
CREATE INDEX ix_cards_nid on cards (nid);
CREATE INDEX ix_cards_sched on cards (did, queue, due);
CREATE INDEX ix_revlog_cid on revlog (cid);
CREATE INDEX ix_revlog_usn on revlog (usn);
CREATE INDEX ix_notes_csum on notes (csum);
""")
c.execute("INSERT INTO col VALUES (1,?,?,?,11,0,0,0,?,?,?,?,?)",
          (crt, now_ms, now_ms, json.dumps(conf), json.dumps(models),
           json.dumps(decks), json.dumps(dconf), "{}"))

all_tags, pos, nid, cid_ = set(), 0, now_ms, now_ms + 500000
manifest = []

for i, card in enumerate(CARDS):
    cp = card.get('cp')
    concept_id = f"{COURSE_ID}:{TOPIC_ID}:{slug(card['cid'])}"
    tags = [f"premedos::type::{card['ct']}",
            f"premedos::mechanism::{cp or 'basic'}",
            f"premedos::difficulty::{card['d']}",
            f"premedos::salience::{card['sal']}",
            f"premedos::preset::{PRESET}",
            f"premedos::mode::{MODE}",
            f"biol103::lesson2::{slug(card['cid'])}"]
    if cp == 'enumerated-list':
        tags.append(f"premedos::list::{'ordered' if card.get('lo') else 'unordered'}")
    if card.get('dir'):
        tags.append(f"premedos::exemplar::{card['dir']}")
    if card.get('ct') in ('COMPARISON', 'EXEMPLAR') or card.get('rel'):
        tags.append("premedos::relational")
    if card.get('kind') == 'framework':
        tags.append("premedos::framework")

    # mindset: the verb telling the student how to answer (Andy, Aug 2026)
    MINDSET = {'BASIC_QA': ('m-say', 'say it'), 'CLOZE': ('m-say', 'say it'),
               'CONCEPTUAL': ('m-explain', 'explain it'),
               'COMPARISON': ('m-connect', 'connect it'),
               'EXEMPLAR': ('m-connect', 'connect it'),
               'PROCESS': ('m-say', 'say it'),
               'APPLICATION': ('m-use', 'use it'),
               'FREE_RECALL': ('m-blurt', 'blurt it')}
    mcls, mverb = MINDSET[card['ct']]
    if card['ct'] == 'CLOZE':
        tname = {'definition': 'definition', 'enumerated-list': 'list',
                 'single': 'fill in', 'independent': 'fill in'}[cp]
    elif card['ct'] == 'EXEMPLAR':
        tname = 'example \u2192 concept' if card['dir'] == 'instance-to-concept' else 'concept \u2192 example'
    elif card['ct'] == 'COMPARISON':
        tname = 'comparison'
    elif card['ct'] == 'CONCEPTUAL':
        tname = 'conceptual'
    elif card['ct'] == 'APPLICATION':
        tname = 'application'
    elif card['ct'] == 'FREE_RECALL':
        tname = 'free recall'
    else:
        tname = 'recall'
    type_html = f'<span class="verb">{mverb}</span><span class="tname">{tname}</span>'
    tags.append(f"premedos::mindset::{mcls[2:]}")
    all_tags.update(tags)
    tagstr = " " + " ".join(tags) + " "

    ex = esc(card.get('ex', ''))
    if card['ct'] == 'FREE_RECALL':
        fields = [blurt_front(card['f']), blurt_back(card['items']), ex,
                  type_html, mcls, concept_id, esc(card['src']), SPEC]
        mid, ords = MID_BASIC, [0]
    elif cp:
        # COMPARISON cards record their axis (FC-19c) where the student can see it
        cz_ex = ex
        if card.get('ax'):
            axis = f'<div class="axis"><b>Axis:</b> {hard_esc(card["ax"])}</div>'
            cz_ex = axis + ex
        fields = [esc(card['cz']), cz_ex, type_html, mcls, concept_id, esc(card['src']), SPEC]
        mid, ords = MID_CLOZE, sorted({int(n) for n in re.findall(r"\{\{c(\d+)::", card['cz'])})
        ords = [o - 1 for o in ords]
    else:
        b_ex = ex
        if card.get('ax'):
            axis = f'<div class="axis"><b>Axis:</b> {hard_esc(card["ax"])}</div>'
            b_ex = axis + ex
        fields = [esc(card['f']), esc(card['b']), b_ex, type_html, mcls, concept_id, esc(card['src']), SPEC]
        mid, ords = MID_BASIC, [0]

    flds = "\x1f".join(fields)
    c.execute("INSERT INTO notes VALUES (?,?,?,?,-1,?,?,?,?,0,'')",
              (nid, guid64(concept_id + str(i)), mid, now_ms // 1000,
               tagstr, flds, fields[0], csum(fields[0])))
    for o in ords:
        pos += 1
        c.execute("INSERT INTO cards VALUES (?,?,?,?,?,-1,0,0,?,0,0,0,0,0,0,0,0,'')",
                  (cid_, nid, DID_SUB, o, now_ms // 1000, pos))
        cid_ += 1
    manifest.append((i + 1, card["ct"], cp or "basic", len(ords), card["cid"]))
    nid += 1

conf["nextPos"] = pos + 1
c.execute("UPDATE col SET conf=?, tags=?", (json.dumps(conf),
          json.dumps({t: -1 for t in sorted(all_tags)})))
con.commit()
con.close()

meta = {"" : ""}
with zipfile.ZipFile(OUT, "w", zipfile.ZIP_DEFLATED) as z:
    z.write(db, "collection.anki2")
    z.writestr("media", "{}")
os.remove(db)

notes_n = len(CARDS)
cards_n = pos
print(f"wrote {OUT}")
print(f"  notes: {notes_n}   generated Anki cards: {cards_n}")
print(f"  size: {os.path.getsize(OUT)/1024:.1f} KB")
