"""Source-grounded authored UI fixtures; no empirical course/provider claims."""
from pathlib import Path
import argparse,copy,json,shutil,hashlib
ROOT=Path(__file__).parent

def build(out):
    out.mkdir(parents=True,exist_ok=True);materials=out/'materials';materials.mkdir(exist_ok=True)
    for p in (ROOT/'visual-repertoire-assets').iterdir():shutil.copyfile(p,materials/p.name)
    raw=(materials/'FICTIONAL-REFERENCE.md').read_text();parts=raw.split('\n## ');excerpts=[];lookup={}
    for i,p in enumerate(parts[1:]):
        heading,body=p.split('\n',1);id='ref-'+str(i+1);lookup[heading]=id;excerpts.append({'id':id,'location':'Section: '+heading,'text':body.strip()})
    def ev(*headings,image=False):return {'sourceIds':(['ref'] if headings else [])+(['image'] if image else []),'excerptIds':[lookup[h] for h in headings],'assetIds':['source-image'] if image else []}
    def block(id,type,title,e,**props):return {'id':id,'type':type,'title':title,'provenance':'clarification',**e,**props}
    def item(id,label,e,**props):return {'id':id,'label':label,**e,**props}
    blocks=[]
    blocks.append({'id':'compare-cards','type':'table','provenance':'source',**ev('Comparison'),'columns':['Dimension','Text card','Image card'],'rows':[['Label','Written label','Written label'],['Representation','Written description; no source picture','Supplied source picture; description of visible content'],['Reference','Retains reference ID','Retains reference ID']]})
    def diagram(id,kind,title,heading,labels,edges):
        evidence=ev(heading);nodes=[item(id+'-n'+str(i),v,evidence) for i,v in enumerate(labels)];es=[{'id':id+'-e'+str(i),'from':nodes[a]['id'],'to':nodes[b]['id'],'relation':rel,'label':label,**evidence} for i,(a,b,rel,label) in enumerate(edges)];return {'id':id,'type':'study-diagram','provenance':'clarification',**evidence,'kind':kind,'title':title,'nodes':nodes,'edges':es}
    blocks.append(diagram('route-card','decision-tree','Route a fictional archive card','Decisions',['Is the label readable?','Labeled collection','Manual review'],[(0,1,'other','Yes — readable'),(0,2,'other','No — unreadable')]))
    blocks.append(diagram('collection-tree','hierarchy','Fictional collection contents','Hierarchy',['Collection','Text card','Image card','Written description','Supplied picture'],[(0,1,'contains','contains'),(0,2,'contains','contains'),(1,3,'contains','contains'),(2,4,'contains','contains')]))
    blocks.append(diagram('access-chain','causal-chain','Stipulated access rule','Cause and effect',['Access switch disabled','Opening blocked','Card display'],[(0,1,'causes','causes under this stipulated rule'),(1,2,'inhibits','prevents')]))
    inspected=json.loads((materials/'IMAGE-INSPECTION.json').read_text());anchor=inspected['observedTipNormalized'];imageev=ev('Image annotation reference',image=True)
    blocks.append(block('label-source-image','annotated-figure','An actual source-image anchor',imageev,assetId='source-image',caption='Unchanged authored classroom-task fixture',alt='An authored classroom rule, an outlined triangle and four unmarked response options.',context='Fictional UI test material; use the supplied shape and written rule.',annotations=[item('shape-top','Top corner of the displayed shape',imageev,**anchor,positionBasis='Actual decoded 1100×530 source: top triangle pixels at x165,y240, inspected visually and verified within its pixel bounds. Normalized coordinates are x165/1100,y240/530.')]))
    ordinal={'mode':'ordinal','unit':None,'minimum':None,'maximum':None};numeric={'mode':'numeric','unit':'minutes after 09:00','minimum':0,'maximum':25};eventev=ev('Timeline')
    for mode in ['ordinal','numeric']:
        events=[item('time-'+mode+'-'+str(i),label,eventev,detail='Fictional scheduled stage; no causal claim.',timeLabel=time,value=(value if mode=='numeric' else None)) for i,(label,time,value) in enumerate([('Collect','09:00',0),('Label','09:10',10),('Check','09:25',25)])]
        blocks.append(block('schedule-'+mode,'timeline','Fictional schedule — '+mode,eventev,orderingBasis='The authored reference supplies Collect before Label before Check and explicit scheduled times.',axis=copy.deepcopy(ordinal if mode=='ordinal' else numeric),events=events))
    setev=ev('Set overlap');sets=[item('set-text','Text-described',setev),item('set-image','Image-supported',setev)];regions=[]
    for id,membership,card in [('only-text',['set-text'],'Card A'),('both',['set-text','set-image'],'Card C'),('only-image',['set-image'],'Card B')]:regions.append({'id':id,'setIds':membership,'items':[{'id':'member-'+id,'text':card,**setev}]})
    blocks.append(block('card-membership','venn','Fictional card membership',setev,sets=sets,regions=regions))
    sequenceev=ev('Sequence strip',image=True);steps=[]
    for i,(label,detail) in enumerate([('Read the written rule','Identify what each symbol means in this fictional task.'),('Inspect the displayed shape','Use the unchanged supplied image.'),('Apply the rule','Choose the response; the sequence itself does not disclose it.')]):
        has=i==1;steps.append(item('task-step-'+str(i),label,ev('Sequence strip',image=has),detail=detail,assetId='source-image' if has else None,alt='Unmarked authored source task with its rule and displayed shape.' if has else None))
    blocks.append(block('task-strip','sequence-strip','Ordered task actions',sequenceev,orderingBasis='The authored instructions explicitly order reading, inspecting and applying.',steps=steps))
    problemev=ev('Timeline');solutionev=ev('Timeline','Worked example');workedsteps=[item('elapsed-step-1','Identify the minute values',solutionev,explanation='Both scheduled times are in the 09:00 hour. Label is at minute 10 and Check at minute 25.'),item('elapsed-step-2','Subtract in the stated order',solutionev,explanation='25 − 10 = 15 minutes.')]
    blocks.append(block('elapsed-worked','worked-example','Time between two scheduled stages',solutionev,problem='The fictional schedule reaches Label at 09:10 and Check at 09:25. How many minutes are scheduled between them?',problemEvidence=problemev,solutionEvidence=solutionev,stimulusBlockIds=[],steps=workedsteps,answer='15 minutes.',check='The result is positive because Check is later in the same hour. These are fictional scheduled times, not measured observations.'))
    orev=ev('Ordinal continuum');points=[item('readiness-'+str(i),label,orev,detail=detail,value=None) for i,(label,detail) in enumerate([('Unsorted','First named stage.'),('Labeled','The sample folder is at this stage.'),('Checked','Later named stage; no interval or duration implied.')])]
    blocks.append(block('readiness-scale','continuum','Fictional readiness stages',orev,orderingBasis='The reference orders Unsorted, Labeled and Checked without numeric distances.',axis=copy.deepcopy(ordinal),points=points))
    nrev=ev('Numeric scale');points=[item('numeric-score-'+str(i),label,nrev,detail='Invented UI display test value, not a learner score or empirical measurement.',value=value) for i,(label,value) in enumerate([('Lower anchor',0),('Middle anchor',5),('Sample marker',7),('Upper anchor',10)])]
    blocks.append(block('test-score-scale','continuum','An explicitly fictional numeric scale',nrev,orderingBasis='The authored reference explicitly supplies a 0–10 point domain, 0/5/10 anchors and sample marker 7.',axis={'mode':'numeric','unit':'points','minimum':0,'maximum':10},points=points))
    practice={'id':'source-question','type':'practice','provenance':'source',**imageev,'prompt':'Which response follows the displayed shape? A. Left B. Right C. Both D. Not specified','answer':'A. Left.','rationale':'The supplied fictional rule maps the displayed triangle to LEFT. The figure has no marked answer.','stimulusBlockIds':['label-source-image']}
    source={'id':'ref','title':'Authored visual-contract reference','role':'other','access':'read','inspected':'Complete local authored fixture reference, all named sections. Explicitly fictional/non-empirical UI material, not a course or provider trial.','limitations':['Authored UI fixture facts establish only the intended test semantics.'],'used':True,'excerpts':excerpts}
    imagesource={'id':'image','title':'Authored PSYC101 classroom-task test image','role':'other','access':'read','inspected':'Actual unchanged source PNG viewed and decoded at 1100×530; top triangle anchor independently derived from the visible pixel region. Printed PSYC101 label is fictional fixture context deliberately used as UI reference for DEMO000.','limitations':['A labelled synthetic UI source, not student coursework or empirical scientific evidence.'],'used':True,'excerpts':[]}
    req={'id':'fixture-requirement','kind':'student-request','text':'Display the agreed structured visual families using the supplied fictional reference and actual fixture image.','authority':'selected-material',**ev(*lookup.keys(),image=True),'status':'supported','basis':'The authored fixture contains explicit comparison, sequence, causal-rule, chronology, membership, axis and worked-problem facts. This tests UI/contract behavior, not course learning quality.','sectionIds':['fixture-teaching','fixture-practice'],'nextStep':None}
    groups=[('compare','Compare cards',['compare-cards']),('route','Route cards',['route-card']),('hierarchy','Collection hierarchy',['collection-tree']),('causal','Stipulated access chain',['access-chain']),('annotation','Supplied-image annotation',['label-source-image']),('schedule','Schedule: order and elapsed time',['schedule-ordinal','schedule-numeric']),('membership','Shared membership',['card-membership']),('sequence','Task sequence',['task-strip']),('worked','Worked timing example',['elapsed-worked']),('scales','Readiness and score scales',['readiness-scale','test-score-scale'])]
    byid={b['id']:b for b in blocks};sections=[{'id':'fixture-'+id,'title':title,'purpose':'study-guide','blocks':[byid[x] for x in ids]} for id,title,ids in groups]
    sections.append({'id':'fixture-practice','title':'One supplied fixture question','purpose':'practice','blocks':[practice]});req['sectionIds']=[s['id'] for s in sections]
    package={'format':'premed-os-notebook-package','version':4,'instructionsVersion':'notebook-workflows-draft-4','course':{'code':'DEMO 000','title':'Authored visual-contract fixtures','term':None},'sources':[source,imagesource],'entries':[{'id':'visual-repertoire-demo','revision':1,'baseRevision':None,'title':'Authored visual repertoire — non-empirical UI fixtures','goal':'review','scope':'Contract and renderer demonstration of the agreed visual families; no actual course trial.','request':{'helpStage':None,'classPreferences':'Use actual supplied fixture meanings and preserve neutral question/reveal boundaries.','assessmentFormat':None},'sections':sections,'objectives':[],'requirements':[req],'limitations':['This deliberately exhaustive family showcase is a UI fixture, not a recommended density or visual quota for a student notebook.']}],'assets':[{'id':'source-image','sourceId':'image','location':'Actual authored source PNG, full image','fileName':'authored-classroom-task.png','mimeType':'image/png','originalAssetId':None,'alteration':None}],'visualReview':{'sources':[{'sourceId':'ref','discovery':'complete','imageState':'none-found','inspectedPortions':['Complete authored text reference.'],'unprocessedPortions':[],'limitations':[]},{'sourceId':'image','discovery':'complete','imageState':'images-found','inspectedPortions':['Full actual1100×530PNG viewed/decoded; observed top triangle pixel anchor.'],'unprocessedPortions':[],'limitations':[]}],'candidates':[{'id':'fixture-image-candidate','sourceId':'image','location':'Full authored source PNG','discovered':True,'inspection':'inspected','decision':'selected','assetId':'source-image','reason':'Actual source image for point annotation, sequence-image closure and neutral question-reveal checks.','nextStep':None,'duplicateOf':None,'changedFrom':None}]}}
    (out/'visual-repertoire-v4.json').write_text(json.dumps(package,ensure_ascii=False,indent=2)+'\n');shutil.copyfile(materials/'authored-classroom-task.png',out/'authored-classroom-task.png')
    binding={'format':'premed-os-notebook-asset-index','version':1,'bindings':[{'assetId':'source-image','sha256':inspected['sha256'],'mimeType':'image/png','byteLength':inspected['bytes'],'width':inspected['width'],'height':inspected['height']}]};(out/'bindings.json').write_text(json.dumps(binding,indent=2)+'\n')
    (out/'README.md').write_text('# Authored v4 visual repertoire fixture\n\nEvery fact/time/score/category is explicitly fictional non-empirical UI material, with exact reference excerpts. The source PNG is actual unchanged raster material. This demonstrates each family for app tests, not a format quota, course notebook, provider run or release acceptance. Initial worked-problem evidence is separate from its gated solution evidence. The sole practice question retains a neutral annotated stimulus.\n')
    return package

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--output',type=Path,required=True);a=p.parse_args();build(a.output);print(a.output/'visual-repertoire-v4.json')
