"""Invented structural examples. Never class trials or claimed learning-quality evidence."""
from pathlib import Path
import argparse, copy, hashlib, json
DISCLAIMER='Invented structural fixture. No real course materials or student trial were processed.'
TEXT='A route is an ordered list of stops. A label names one stop. A tag groups stops by a shared feature. Changing a label does not change the route order. Rearranging stops changes the route order. Two stops may share a tag while retaining different labels.'
def source(id,title,text,role='reading',access='read'):
    return dict(id=id,title=title,role=role,access=access,inspected='Complete invented passage printed in the fixture.' if access=='read' else '',limitations=[DISCLAIMER],used=access=='read',excerpts=[dict(id='ex-'+id,location='Invented fixture paragraph 1',text=text)] if access=='read' else [])
def ev(*ids):return dict(sourceIds=list(ids),excerptIds=['ex-'+id for id in ids])
def block(id,type='paragraph',provenance='clarification',sources=('lesson-1',),**props):return dict(id=id,type=type,provenance=provenance,**ev(*sources),**props)
def section(id,title,purpose,blocks):return dict(id=id,title=title,purpose=purpose,blocks=blocks)
def req(id,text,sections,status='supported',kind='objective',authority='selected-material',sources=('lesson-1',),basis='The cited passage supports the teaching in the linked section.',nextStep=None):
    return dict(id=id,text=text,kind=kind,authority=authority,**ev(*sources),status=status,basis=basis,sectionIds=sections,nextStep=nextStep)
def entry(goal,sections,requirements,objectives=None):return dict(id='fixture-'+goal,revision=1,baseRevision=None,title='Routes, labels and tags',goal=goal,scope=DISCLAIMER,request=dict(helpStage=None,classPreferences='Define terms before comparisons.',assessmentFormat=None),sections=sections,requirements=requirements,objectives=objectives or [],limitations=[DISCLAIMER])
def package(e,sources=None):return dict(format='premed-os-notebook-package',version=2,instructionsVersion='notebook-workflows-draft-2',course=dict(code='DEMO 101',title='Invented Route Workshop',term=None),sources=sources or [source('lesson-1','Invented lesson 1',TEXT)],entries=[e])
def practice(id='practice-1',sources=('lesson-1',)):
    return block(id,'practice','generated-practice',sources,prompt='Hypothetical route: North then South. Both stops have the tag quiet. Rename North to Oak without moving it. State the resulting order and whether sharing quiet makes the two stop labels identical.',answer='Oak then South. Their labels remain different despite the shared tag.',rationale='Renaming changes a label, not position, so the first stop is still first. A tag groups stops by feature; the handout explicitly permits shared tags with different labels. Confusing a shared tag with a shared label would erase this distinction.')
def review():
    sections=[section('orientation','At a glance','study-guide',[block('orientation-text',text='A route records order, a label identifies a stop, and a tag groups stops by a feature. Keep these three jobs distinct when describing a change.')]),section('teaching','Understand the change','study-guide',[block('mechanism',text='Renaming a stop changes how it is named while preserving its place in the route. Moving a stop changes the order. Tags address a different question: which stops share a feature? Thus two differently named stops can share a tag without becoming the same label.'),block('compare','table',columns=['Action','What changes'],rows=[['Rename a stop','Its label; order stays fixed'],['Rearrange stops','Route order changes']])]),section('practice','Apply the distinction','practice',[practice()]),section('synthesis','Remember and connect','study-guide',[block('memory','bullets',items=['Memorize: route = ordered stops; label = stop name; tag = shared feature.','Understand: identifying what changed requires distinguishing a new name from a new position.'])])]
    objective=dict(id='obj-route',requirementId='req-route',title='Study objective: Distinguish route order, labels and tags.',origin='derived',**ev('lesson-1'),freeRecallCues=['Without notes, explain the distinct jobs of route, label and tag.'],understand=['A route specifies an order of stops.','A label names an individual stop.','A tag groups stops through a shared feature.','Renaming a stop preserves its route position.','Rearranging stops changes route order.','Stops sharing a tag can still have different labels.'],beAbleToDo=['Predict route order after a rename with no movement.','Distinguish a shared tag from identical stop labels in a supplied example.'],watchFor=['Do not treat a shared tag as proof that two labels are identical.'],practiceBlockIds=['practice-1'],evidenceLimit=None)
    return package(entry('review',sections,[req('req-route',objective['title'],['teaching','practice','synthesis'])],[objective]))
def assessment(multi=False):
    scope='Compare route order, labels and tags. Apply the rename rule to an example. Short explanations and original applications are the stated format.'
    sources=[source('lesson-1','Invented lesson 1',TEXT),source('scope','Invented assessment scope',scope,'assessment-scope')]
    p=practice()
    sections=[section('prepare','Connect names, groups and order','preparation',[block('teach',text='Order, naming and grouping answer different questions. A route fixes sequence; labels name individual stops; tags link stops by shared features. A rename preserves order, so first identify whether a task changes a name or a position before predicting the route.')]),section('practice','Application practice','practice',[p])]
    requirements=[req('req-compare','Compare route order, labels and tags.',['prepare'],kind='assessment',authority='official',sources=('scope','lesson-1'),basis='Scope excerpt establishes the requirement; lesson 1 supplies the comparison.'),req('req-apply','Apply the rename rule to an example.',['prepare','practice'],kind='assessment',authority='official',sources=('scope','lesson-1'),basis='Scope establishes the demand; lesson 1 supports the solution in the original hypothetical practice.')]
    requirements.append(req('req-format','Short explanations and original applications are the stated format.',['prepare','practice'],kind='assessment',authority='official',sources=('scope',),basis='The scope excerpt establishes the format; preparation provides short explanations and practice provides an original hypothetical application with a worked answer.'))
    if multi:
        requirements[-1]['sectionIds'].append('cross-practice')
        sources += [source('lesson-2','Invented lesson 2','A display filter hides stops that lack a selected tag without changing the stored route order.'),source('notes','Invented personal notes','Question: If I cannot see a stop, was it deleted?','personal-notes'),source('supplement','Invented reading','A hidden stop remains in the stored route. Hiding is a display change, not deletion.'),source('scan','Invented unreadable scan','',access='unreadable')]
        sources[1]['excerpts'][0]['text']+=' Compare a rename with a display filter. Do not cover route sorting algorithms.'
        sections[0]['blocks'] += [block('filter',sources=('lesson-1','lesson-2'),text='A display filter changes which stops appear according to a selected tag. It leaves the stored order intact, just as renaming leaves order intact, although the two actions change different things.'),block('qualify',sources=('supplement','notes'),text='The reading distinguishes hiding from deletion. This addresses the question in the personal notes: lack of visibility alone does not mean a stop was deleted. The note is a student question; the reading supplies the explanation.')]
        sections += [section('cross-practice','Connect both lessons','practice',[block('cross','practice','generated-practice',('lesson-1','lesson-2','supplement'),prompt='Hypothetical stored route: North (quiet), South (busy). Rename North to Oak, then filter the display to quiet. State the visible stop, the stored route, and whether South was deleted.',answer='Visible: Oak. Stored route: Oak then South. South was hidden, not deleted.',rationale='Renaming changes the first label without reordering. The filter displays stops tagged quiet, so only Oak appears. The reading establishes that hidden stops remain stored; South therefore remains second.')]),section('excluded','Explicit boundary','next-steps',[block('scope-gap','gap',sources=('scope',),text='Sorting algorithms are explicitly excluded by the invented scope.',nextStep='Keep sorting outside this assessment preparation unless the scope is explicitly revised.')])]
        requirements += [req('req-filter','Compare a rename with a display filter.',['prepare','cross-practice'],kind='assessment',authority='official',sources=('scope','lesson-1','lesson-2','supplement'),basis='Scope establishes the comparison. Lesson 1 teaches renaming; lesson 2 and the reading explain display filtering and retention.'),req('req-excluded','Do not cover route sorting algorithms.',['excluded'],'out-of-scope','assessment','official',('scope',),'The supplied scope explicitly excludes this content.','Revisit only if the scope is explicitly revised.')]
    e=entry('assessment',sections,requirements)
    e['request']['assessmentFormat']='Short explanations and original applications.'
    return package(e,sources)
def assignment(hint=False):
    prompt='Plan a route with two differently labeled stops that share one tag. Write the final route description.'
    sources=[source('lesson-1','Invented lesson 1',TEXT),source('task','Invented assignment prompt',prompt,'assignment-prompt'),source('request','Invented student request','Give only one hint for planning; do not write the final route.' if hint else 'Help me plan; leave the final route description for me.','other')]
    content=block('help',text='Start by separating the two jobs: choose distinct names for the stops, then identify a feature they could share. A common tag does not require identical names.' if hint else 'Plan in two steps: choose different labels for the two stops; then choose a feature both stops share and use it as their tag. Keep the proposed order explicit when you later write the route. The shared tag groups the stops without collapsing their different labels.')
    sections=[section('workspace','One planning hint' if hint else 'Plan the route','workspace',[content]),section('next','Your next step','next-steps',[block('boundary','gap',sources=('request','task'),text='The final route description is outside the requested help stage.',nextStep='Write your own route description after choosing its labels and shared tag.')])]
    requirements=[req('req-plan','Plan a route with two differently labeled stops that share one tag.',['workspace'],'partial' if hint else 'supported','assignment','official',('task','lesson-1'), 'Task text establishes the requirement. The hint identifies the needed distinction; the student still needs to choose labels and a tag.' if hint else 'Task text establishes the requirement; the plan explains how to choose distinct labels and a shared tag. This assesses planning support, not student completion.','Choose the two labels and their shared tag.' if hint else None),req('req-final','Write the final route description.',['next'],'out-of-scope','assignment','official',('task','request'),'The explicit student request limits help to planning, leaving the final description to the student.','Write the description yourself, or explicitly request a later support stage.'),req('req-help',sources[2]['excerpts'][0]['text'],['workspace'],'supported','student-request','student-request',('request','lesson-1'),'The response supplies the requested planning support without a finished route.')]
    e=entry('assignment',sections,requirements);e['request']['helpStage']='one hint only' if hint else 'planning only'
    return package(e,sources)
def missing():
    p=review();p['sources'] += [source('objectives','Invented official objective sheet','Explain how route sorting algorithms optimize travel time.','objectives'),source('unreadable','Invented unreadable algorithm notes','',access='unreadable'),source('uninspected','Invented uninspected appendix','',access='not-accessed')]
    e=p['entries'][0];e['sections'].append(section('missing','Uncovered objective','next-steps',[block('gap','gap',sources=('objectives',),text='The objective sheet states the sorting objective, but supplies no explanation. The algorithm notes were unreadable.',nextStep='Supply a readable explanation of the sorting method and its relationship to travel time.')]))
    e['requirements'].append(req('req-missing','Explain how route sorting algorithms optimize travel time.',['missing'],'missing','objective','official',('objectives',),'This excerpt establishes only the official objective wording; no accessible passage supports teaching or a solution.','Supply readable algorithm teaching before adding a mastery objective.'))
    return p

def build(out):
    out.mkdir(parents=True,exist_ok=True)
    examples={'fixture-review':review(),'fixture-assessment':assessment(),'fixture-assignment':assignment(),'edge-missing-objective':missing(),'edge-multi-lesson-assessment':assessment(True),'edge-stage-limited-assignment':assignment(True)}
    gap=missing();e=gap['entries'][0];e['sections']=e['sections'][-1:];e['requirements']=e['requirements'][-1:];e['objectives']=[];gap['sources']=gap['sources'][1:];examples['edge-gap-only-review']=gap
    partial=review();e=partial['entries'][0];o=e['objectives'][0];o['understand']=o['understand'][:1];o['beAbleToDo']=[];o['watchFor']=[];o['practiceBlockIds']=[];o['evidenceLimit']='The inspected fragment defines route but lacks label, tag, and application details.';o['freeRecallCues']=['Without notes, state what a route records.'];partial['sources'][0]['excerpts'][0]['text']='A route is an ordered list of stops.';partial['sources'][0]['access']='partial';partial['sources'][0]['inspected']='Only the first sentence of the invented handout.';e['sections']=[section('teaching','Available definition','study-guide',[block('definition',text='A route records stops in a specific order. The supplied fragment does not explain the other requested distinctions.')])];e['requirements'][0].update(status='partial',basis='Only route is defined in the available fragment; label and tag distinctions are absent.',sectionIds=['teaching'],nextStep='Supply the missing label and tag explanation.');examples['edge-partial-review']=partial
    unreadable=package(entry('review',[section('missing-material','Material needed','next-steps',[block('all-gap','gap',sources=(),text='The supplied material was unreadable, so no teaching claims or mastery objectives can be supported.',nextStep='Supply readable text or an accessible version of the material.')])],[req('req-review','Review the supplied route material.',['missing-material'],'missing','student-request','student-request',(),'No supplied teaching material could be read. The ledger preserves the explicit student request without claiming an official objective.','Supply readable material and retry this same scope.')]),[source('scan-only','Invented unreadable route scan','',access='unreadable')])
    examples['edge-all-unreadable-review']=unreadable
    revision=copy.deepcopy(examples['fixture-review']);revision['entries'][0]['revision']=2;revision['entries'][0]['baseRevision']=1
    revision['entries'][0]['sections'][0]['blocks'][0]['text']+=' Suggested check: identify which of the three jobs a change affects before predicting the result.'
    examples['fixture-review-revision']=revision
    for name,data in examples.items():(out/(name+'.json')).write_text(json.dumps(data,indent=2)+'\n')
    manifest={'instructionsVersion':'notebook-workflows-draft-2','purpose':'Invented structural fixtures, not real class trials or learning-quality acceptance.','fixtures':{name+'.json':{'sha256':hashlib.sha256((out/(name+'.json')).read_bytes()).hexdigest(),'bytes':len((out/(name+'.json')).read_bytes())} for name in examples}}
    (out/'fixture-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
    return examples
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--output',type=Path,required=True);a=p.parse_args();print('Wrote',len(build(a.output)),'invented structural fixtures.')
